Models/Hangar.cs
using ProyectoPrimerParcial.Utils;

namespace ProyectoPrimerParcial.Models
{
    public class Hangar{
        public int HangarId { get; set; }
        public string? NombreHangar {get;set;}
        public HangarType Sector { get; set; }
        public bool AptoMantenimiento {get;set;} = true;
        public bool oficinas {get;set;} = true;
        public virtual List<Aeronave>? Aeronaves { get; set; }

    }
}

ViewModels/HangarViewModels.cs
using System;
using System.Collections.Generic;
using ProyectoPrimerParcial.Models;

namespace ProyectoPrimerParcial2.ViewModels;

public class HangarViewmodels

{
    public List<Hangar> hangars {get; set; } = new List<Hangar>();

    public String NameFilterHan { get; set; }
    
} 

Controllers/HangarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPrimerParcial.Data;
using ProyectoPrimerParcial.Models;
using ProyectoPrimerParcial.ViewModels;


namespace Test.Controllers
{
    public class HangarController : Controller
    {
        private readonly AeronaveContext _context;

        public HangarController(AeronaveContext context)
        {
            _context = context;
        }

        // GET: Hangar
        public async Task<IActionResult> Index(string nameFilterHan)
        {
            var query = from hangar in _context.Hangar select hangar;

            if (!string.IsNullOrEmpty(nameFilterHan))
            {
                query = query.Where(x => x.NombreHangar.Contains(nameFilterHan));
            }

            var model = new HangarIndexViewmodel();
            model.hangars =await query.ToListAsync();
            
            return _context.Aeronave != null ?
            View(model):
            Problem("Entity set 'AeronaveContex.Aeronave' is null.");
        }

        // GET: Hangar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Hangar == null)
            {
                return NotFound();
            }

            var hangar = await _context.Hangar
                .FirstOrDefaultAsync(m => m.HangarId == id);
            if (hangar == null)
            {
                return NotFound();
            }

            var viewModel = new HangarDetailViewModel();
            viewModel.HangarId = hangar.HangarId;
            viewModel.NombreHangar = hangar.NombreHangar;
            viewModel.Sector = hangar.Sector;
            viewModel.AptoMantenimiento = hangar.AptoMantenimiento;
            viewModel.Aeronaves = hangar.Aeronaves;


            return View(viewModel);
        }

        // GET: Hangar/Create
        public IActionResult Create()
        {
                        ViewData["Aeronaves"] = new SelectList(_context.Aeronave, "AeronaveId", "TipoAeronave",  "instructor.AeronaveId");
            return View();
        }

        // POST: Hangar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HangarId,NombreHangar,Sector,AptoMantenimiento,oficinas")] HangarCreateViewModel hangarView)
        {
            if (ModelState.IsValid)
            {
                var hangar = new Hangar{
                    NombreHangar = hangarView.NombreHangar,
                    Sector = hangarView.Sector,
                    AptoMantenimiento = hangarView.AptoMantenimiento,
                    oficinas = hangarView.oficinas,
                    Aeronaves = hangarView.Aeronaves
                };
                _context.Add(hangar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hangarView);
        }

        // GET: Hangar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Hangar == null)
            {
                return NotFound();
            }

            var hangar = await _context.Hangar.FindAsync(id);
            if (hangar == null)
            {
                return NotFound();
            }


            var viewModel = new HangarEditViewModel();
            viewModel.HangarId = hangar.HangarId;
            viewModel.NombreHangar = hangar.NombreHangar;
            viewModel.Sector = hangar.Sector;
            viewModel.AptoMantenimiento = hangar.AptoMantenimiento;
            viewModel.Aeronaves = hangar.Aeronaves;

            ViewData["Aeronaves"] = new SelectList(_context.Aeronave, "AeronaveId", "TipoAeronave",  "instructor.AeronaveId");
            return View(viewModel);
            // ViewData["Aeronaves"] = new SelectList(_context.Aeronave, "AeronaveId", "TipoAeronave",  "instructor.AeronaveId");
            // return View(hangar);
        }

        // POST: Hangar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HangarId,NombreHangar,Sector,AptoMantenimiento,oficinas,Aeronaves")] Hangar hangar)
        {
            if (id != hangar.HangarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hangar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HangarExists(hangar.HangarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hangar);
        }

        // GET: Hangar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Hangar == null)
            {
                return NotFound();
            }

            var hangar = await _context.Hangar
                .FirstOrDefaultAsync(m => m.HangarId == id);
            if (hangar == null)
            {
                return NotFound();
            }
            var viewModel = new HangarDeleteViewModel();
            // viewModel.HangarId = hangar.HangarId;
            viewModel.NombreHangar = hangar.NombreHangar;
            viewModel.Sector = hangar.Sector;
            viewModel.AptoMantenimiento = hangar.AptoMantenimiento;
            viewModel.Aeronave = hangar.Aeronave;

            return View(viewModel);
        }

        // POST: Hangar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Hangar == null)
            {
                return Problem("Entity set 'AeronaveContext.Hangar'  is null.");
            }
            var hangar = await _context.Hangar.FindAsync(id);
            if (hangar != null)
            {
                _context.Hangar.Remove(hangar);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HangarExists(int id)
        {
            return (_context.Hangar?.Any(e => e.HangarId == id)).GetValueOrDefault();
        }
    }
}

Views/Hangar/Create.cshtml
@model ProyectoPrimerParcial.ViewModels.HangarCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hangar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreHangar" class="control-label"></label>
                <input asp-for="NombreHangar" class="form-control" />
                <span asp-validation-for="NombreHangar" class="text-danger"></span>
            </div>
            <br>
            <label asp-for="Sector" class="control-label"></label>
            <select asp-for="Sector" class="form-control">
            <option value="0">Norte</option>
            <option value="1">Sur</option>
            <option value="2">Este</option>
            <option value="3">Oeste</option>
            </select>            
            <br>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AptoMantenimiento" /> @Html.DisplayNameFor(model => model.AptoMantenimiento)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="oficinas" /> @Html.DisplayNameFor(model => model.oficinas)
                </label>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="Aeronaves" class="control-label"></label>
                <select asp-for="Aeronaves" class="form-control" asp-items="ViewBag.Aeronaves"></select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Hangar/Delete.cshtml
@model ProyectoPrimerParcial.ViewModels.HangarDeleteViewModel;

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Hangar</h1>

<h3>Esta seguro que quiere eliminar este Hangar?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreHangar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreHangar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sector)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sector)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptoMantenimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptoMantenimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.oficinas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.oficinas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aeronaves)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aeronaves)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="HangarId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> 
        <br>
        <br>
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Hangar/Details.cshtml
@model ProyectoPrimerParcial.ViewModels.HangarDetailViewModel;

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle del Hangar</h1>

<div>

    <hr/>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreHangar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreHangar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sector)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sector)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AptoMantenimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AptoMantenimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.oficinas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.oficinas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aeronaves)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aeronaves)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.HangarId" class="btn btn-warning">Editar</a> 
<br>
<br>
    <a asp-action="Index">Volver</a>
</div>

Views/Hangar/Edit.cshtml
@model ProyectoPrimerParcial.ViewModels.HangarEditViewModel;


@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Hangar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HangarId" />
            <div class="form-group">
                <label asp-for="NombreHangar" class="control-label"></label>
                <input asp-for="NombreHangar" class="form-control" />
                <span asp-validation-for="NombreHangar" class="text-danger"></span>
            </div>
            <br>
            <label asp-for="Sector" class="control-label"></label>
            <select asp-for="Sector" class="form-control">
            <option value="0">Norte</option>
            <option value="1">Sur</option>
            <option value="2">Este</option>
            <option value="3">Oeste</option>
            </select>            
            <br>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AptoMantenimiento" /> @Html.DisplayNameFor(model => model.AptoMantenimiento)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="oficinas" /> @Html.DisplayNameFor(model => model.oficinas)
                </label>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="Aeronaves" class="control-label"></label>
                <select asp-for="Aeronaves" class="form-control" asp-items="ViewBag.Aeronaves"></select>
            </div>
            <br>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-success" /> 
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Hangar/Index.cshtml
@model ProyectoPrimerParcial.ViewModels.HangarIndexViewmodel;

@{
    ViewData["Title"] = "Index";
}

<h1>Hangares</h1>

<p>
    <a asp-action="Create" class="btn btn-success">+ Hangar</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Hangar">
        <div class="col-6 form-group">
            <input class="form-control" asp-for="NameFilterHan" />
        </div>
        <br>
        <button class="btn btn-info" type="submit">Buscar</button>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreHangar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sector)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AptoMantenimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.oficinas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aeronaves)
            </th>
            <th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.hangars) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreHangar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sector)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AptoMantenimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.oficinas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aeronaves)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.HangarId"class="btn btn-warning">Modificar</a> 
                <a asp-action="Details" asp-route-id="@item.HangarId" class="btn btn-primary">Detalle</a> 
                <a asp-action="Delete" asp-route-id="@item.HangarId"  class="btn btn-danger" onclick="return confirm('¿Esta seguro que quiere eliminar este instructor?')">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>