Models/Instructor.cs
using ProyectoPrimerParcial.Utils;

namespace ProyectoPrimerParcial.Models
{
    public class Instructor
    {
        public int InstructorId { get; set; }
        public string? NombreInstructor {get; set;}
        public string? Apellido {get; set;}
        public int DNI {get; set;}
        public LicenciaType TipoLicencia { get; set; }
        public int NumeroLicencia {get; set;}
        public DateTime FechaExpedicion {get;set;}
        public bool EnActividad {get;set;} = true;
        public int AeronaveId { get; set; }
        public virtual Aeronave? Aeronave { get; set; }
        
    }
}

Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPrimerParcial.Data;
using ProyectoPrimerParcial.Models;
using ProyectoPrimerParcial.ViewModels;



namespace Test.Controllers
{
    public class InstructorController : Controller
    {
        private readonly AeronaveContext _context;

        public InstructorController(AeronaveContext context)
        {
            _context = context;
        }

        // GET: Instructor
        public async Task<IActionResult> Index(string nameFilterIns)
        {
            var query = from instructor in _context.Instructor.Include(i => i.Aeronave) select instructor;

            if (!string.IsNullOrEmpty(nameFilterIns))
            {
                query = query.Where(x => x.NombreInstructor.Contains(nameFilterIns) || x.Apellido.Contains(nameFilterIns) || x.DNI.ToString() == nameFilterIns);
            }

            var model = new InstructorIndexViewmodels();
            model.instructors =await query.ToListAsync();
            
            return _context.Aeronave != null ?
            View(model):
            Problem("Entity set 'AeronaveContex.Aeronave' is null.");

        }

        // GET: Instructor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Instructor == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructor
                .Include(i => i.Aeronave)
                .FirstOrDefaultAsync(m => m.InstructorId == id);
            if (instructor == null)
            {
                return NotFound();
            }

            var viewModel  = new InstructorDetailViewModel();
                viewModel.NombreInstructor = instructor.NombreInstructor;
                viewModel.Apellido = instructor.Apellido;
                viewModel.DNI = instructor.DNI;
                viewModel.TipoLicencia = instructor.TipoLicencia;
                viewModel.NumeroLicencia = instructor.NumeroLicencia;
                viewModel.FechaExpedicion = instructor.FechaExpedicion;
                viewModel.EnActividad = instructor.EnActividad;
                viewModel.Aeronave = instructor.Aeronave;

            return View(viewModel);
        }
        // GET: Instructor/Create
        public IActionResult Create()
        {//esta linea esta en la version sin ViewModels
            ViewData["AeronaveId"] = new SelectList(_context.Aeronave, "AeronaveId", "TipoAeronave");
            return View();
        }

        // POST: Instructor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstructorId,NombreInstructor,Apellido,DNI,TipoLicencia,NumeroLicencia,FechaExpedicion,EnActividad,AeronaveId")] InstructorCreateViewModel instructorView)
        {
            if (ModelState.IsValid)
            {
                var instructor = new Instructor{
                    NombreInstructor = instructorView.NombreInstructor,
                    Apellido = instructorView.Apellido,
                    DNI = instructorView.DNI,
                    TipoLicencia = instructorView.TipoLicencia,
                    NumeroLicencia = instructorView.NumeroLicencia,
                    FechaExpedicion = instructorView.FechaExpedicion,
                    EnActividad = instructorView.EnActividad,
                    Aeronave = instructorView.Aeronave
                    
                };
                _context.Add(instructor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AeronaveId"] = new SelectList("AeronaveId", "TipoAeronave");
            return View(instructorView);
        }

        // GET: Instructor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Instructor == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructor.FindAsync(id);
            if (instructor == null)
            {
                return NotFound();
            }


            var viewModel  = new InstructorEditViewModel();
            viewModel.NombreInstructor = instructor.NombreInstructor;
            viewModel.Apellido = instructor.Apellido;
            viewModel.DNI = instructor.DNI;
            viewModel.TipoLicencia = instructor.TipoLicencia;
            viewModel.NumeroLicencia = instructor.NumeroLicencia;
            viewModel.FechaExpedicion = instructor.FechaExpedicion;
            viewModel.EnActividad = instructor.EnActividad;
            viewModel.AeronaveId = instructor.AeronaveId;

            ViewData["AeronaveId"] = new SelectList(_context.Aeronave, "AeronaveId", "TipoAeronave");
            return View(viewModel);
        }

        // POST: Instructor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstructorId,NombreInstructor,Apellido,DNI,TipoLicencia,NumeroLicencia,FechaExpedicion,EnActividad")] Instructor instructor)
        {
            if (id != instructor.InstructorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instructor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstructorExists(instructor.InstructorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var viewModel  = new InstructorEditViewModel();
            viewModel.NombreInstructor = instructor.NombreInstructor;
            viewModel.Apellido = instructor.Apellido;
            viewModel.DNI = instructor.DNI;
            viewModel.TipoLicencia = instructor.TipoLicencia;
            viewModel.NumeroLicencia = instructor.NumeroLicencia;
            viewModel.FechaExpedicion = instructor.FechaExpedicion;
            viewModel.EnActividad = instructor.EnActividad;
            viewModel.AeronaveId = instructor.AeronaveId;

            ViewData["AeronaveId"] = new SelectList(_context.Aeronave, "AeronaveId", "TipoAeronave",  "instructor.AeronaveId");
            return View(viewModel);
        }

        // GET: Instructor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Instructor == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructor
                .Include(i => i.Aeronave)
                .FirstOrDefaultAsync(m => m.InstructorId == id);
            if (instructor == null)
            {
                return NotFound();
            }
            var viewModel  = new InstructorDeleteViewModel();
            viewModel.NombreInstructor = instructor.NombreInstructor;
            viewModel.Apellido = instructor.Apellido;
            viewModel.DNI = instructor.DNI;
            viewModel.TipoLicencia = instructor.TipoLicencia;
            viewModel.NumeroLicencia = instructor.NumeroLicencia;
            viewModel.FechaExpedicion = instructor.FechaExpedicion;
            viewModel.EnActividad = instructor.EnActividad;
            viewModel.Aeronave = instructor.Aeronave; 

            return View(viewModel);
        }

        // POST: Instructor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Instructor == null)
            {
                return Problem("Entity set 'AeronaveContext.Instructor'  is null.");
            }
            var instructor = await _context.Instructor.FindAsync(id);
            if (instructor != null)
            {
                _context.Instructor.Remove(instructor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstructorExists(int id)
        {
            return (_context.Instructor?.Any(e => e.InstructorId == id)).GetValueOrDefault();
        }
    }
}

Views/Instructor/Create.cshtml
@model ProyectoPrimerParcial.ViewModels.InstructorCreateViewModel



@{
    ViewData["Title"] = "Create";
}

<h1>Crear instructor</h1>

<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreInstructor" class="control-label"></label>
                <input asp-for="NombreInstructor" class="form-control" />
                <span asp-validation-for="NombreInstructor" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>



            <br>
            <label asp-for="TipoLicencia" class="control-label"></label>
            <select asp-for="TipoLicencia" class="form-control">
            <option value="0">Comercial</option>
            <option value="1">Carga</option>
            <option value="2">Militar</option>
            </select>            
            <br>



            <div class="form-group">
                <label asp-for="NumeroLicencia" class="control-label"></label>
                <input asp-for="NumeroLicencia" class="form-control" />
                <span asp-validation-for="NumeroLicencia" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
            <label class="form-label" >Fecha de expedicion</label>
            <input class="form-control" asp-for="FechaExpedicion" />
            </div>
            <br>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EnActividad" /> @Html.DisplayNameFor(model => model.EnActividad)
                </label>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="AeronaveId" class="control-label"></label>
                <select asp-for="AeronaveId" class="form-control" asp-items="ViewBag.AeronaveId"></select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>

        </form>
    </div>
</div>

<div><br>
<br>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Instructor/Delete.cshtml
@model ProyectoPrimerParcial.ViewModels.InstructorDeleteViewModel;

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar instructor</h1>

<h3>Esta seguro que quiere eliminar este instructor?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreInstructor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreInstructor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoLicencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoLicencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroLicencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroLicencia)
        </dd>
            <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaExpedicion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaExpedicion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnActividad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnActividad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aeronave)
        </dt>
        <dl class = "col-sm-10">
            @Html.DisplayFor(model => model.Aeronave.TipoAeronave)
        </dl>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InstructorId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <br>
        <br> 

        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Instructor/Details.cshtml
@model ProyectoPrimerParcial.ViewModels.InstructorDetailViewModel;

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle del instructor</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreInstructor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreInstructor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoLicencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoLicencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroLicencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroLicencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaExpedicion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaExpedicion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnActividad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnActividad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aeronave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aeronave.TipoAeronave)
        </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.InstructorId" class="btn btn-warning">Editar</a>

    <br>
    <br> 
    <a asp-action="Index">Volver</a>
</div>

Views/Instructor/Edit.cshtml
@model ProyectoPrimerParcial.ViewModels.InstructorEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar instructor</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InstructorId" />
            <div class="form-group">
                <label asp-for="NombreInstructor" class="control-label"></label>
                <input asp-for="NombreInstructor" class="form-control" />
                <span asp-validation-for="NombreInstructor" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <br>
            <label asp-for="TipoLicencia" class="control-label"></label>
            <select asp-for="TipoLicencia" class="form-control">
            <option value="0">Comercial</option>
            <option value="1">Carga</option>
            <option value="2">Militar</option>
            </select> 
            <br>
            <div class="form-group">
                <label asp-for="NumeroLicencia" class="control-label"></label>
                <input asp-for="NumeroLicencia" class="form-control" />
                <span asp-validation-for="NumeroLicencia" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
            <label asp-for="FechaExpedicion" class="control-label"></label>
            <input asp-for="FechaExpedicion" class="form-control" />
            <span asp-validation-for="FechaExpedicion" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group form-check">
                <label class="form-check-label">
                <input class="form-check-input" asp-for="EnActividad" /> @Html.DisplayNameFor(model => model.EnActividad)
                </label>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="AeronaveId" class="control-label"></label>
                <select asp-for="AeronaveId" class="form-control" asp-items="ViewBag.AeronaveId"></select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<br>
<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Instructor/Index.cshtml
@model ProyectoPrimerParcial.ViewModels.InstructorIndexViewmodels;

@{
    ViewData["Title"] = "Index";
}

<h1>Instructores de vuelo</h1>



<p>
    <a asp-action="Create" class="btn btn-success"> + Instructor</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Instructor">
        <div class="col-6 form-group">
            <input class="form-control" asp-for="NameFilterIns"/>
        </div>
        <br>
        <button class="btn btn-info" type="submit">Buscar</button>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreInstructor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoLicencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroLicencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaExpedicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aeronave)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.instructors) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreInstructor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoLicencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroLicencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaExpedicion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aeronave.TipoAeronave)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.InstructorId" class="btn btn-warning">Modificar</a> 
                <a asp-action="Details" asp-route-id="@item.InstructorId" class="btn btn-primary">Detalle</a> 
                <a asp-action="Delete" asp-route-id="@item.InstructorId"  class="btn btn-danger" onclick="return confirm('¿Esta seguro que quiere eliminar este instructor?')">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>