Models/Aeronave.cs
namespace ProyectoPrimerParcial.Models
{
    public class Aeronave
    {
        public int AeronaveId { get; set; }
        public DateTime FechaFabricacion {get;set;}
        public string? TipoAeronave {get; set;}
        public ICollection<Instructor> InstructorList { get; set; } = new List<Instructor>();
        public virtual List<Hangar>? Hangars { get; set; }

    }
}

ViewModels/AeronaveViewModel.cs
using System;
using System.Collections.Generic;
using ProyectoPrimerParcial.Models;

namespace ProyectoPrimerParcial2.ViewModels;

public class AeronaveViewmodels

{
    public List<Aeronave> aeronaves {get; set; } = new List<Aeronave>();

    public String NameFilter { get; set; }
    
} 

Controllers/AeronaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPrimerParcial.Data;
using ProyectoPrimerParcial.Models;
using ProyectoPrimerParcial.ViewModels;

namespace Test.Controllers
{
    public class AeronaveController : Controller
    {
        private readonly AeronaveContext _context;

        public AeronaveController(AeronaveContext context)
        {
            _context = context;
        }

        // GET: Aeronave
        // public async Task<IActionResult> Index(string nameFilter)
        public async Task<IActionResult> Index(string nameFilter ,[Bind("TipoAeronave,FechaFabricacion")] AeronaveCreateViewModel aeronaveView)


        {
            var query = from aeronave in _context.Aeronave select aeronave;

            if (!string.IsNullOrEmpty(nameFilter))
            {
                query = query.Where(x => x.TipoAeronave.Contains(nameFilter));
            }

            var model = new AeronaveIndexViewmodels();
            model.aeronaves =await query.ToListAsync();
            
            return _context.Aeronave != null ?
            View(model):
            Problem("Entity set 'AeronaveContex.Aeronave' is null.");

        }



        // GET: Aeronave/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Aeronave == null)
            {
                return NotFound();
            }

            var aeronave = await _context.Aeronave
                .FirstOrDefaultAsync(m => m.AeronaveId == id);
            if (aeronave == null)
            {
                return NotFound();
            }

            var viewModel = new AeronaveDetailViewModel();
            viewModel.FechaFabricacion = aeronave.FechaFabricacion;
            viewModel.TipoAeronave = aeronave.TipoAeronave;
            

            return View(viewModel);
        }

        // GET: Aeronave/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aeronave/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoAeronave,FechaFabricacion")] AeronaveCreateViewModel aeronaveView)
        {
            if (ModelState.IsValid)
            {
                var aeronave = new Aeronave{
                    FechaFabricacion = aeronaveView.FechaFabricacion,
                    TipoAeronave = aeronaveView.TipoAeronave,
                };
                _context.Add(aeronave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aeronaveView);
        }

        // GET: Aeronave/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Aeronave == null)
            {
                return NotFound();
            }

            var aeronave = await _context.Aeronave.FindAsync(id);
            if (aeronave == null)
            {
                return NotFound();
            }

            var viewModel = new AeronaveEditViewModel();
            viewModel.FechaFabricacion = aeronave.FechaFabricacion;
            viewModel.TipoAeronave = aeronave.TipoAeronave;
            

            return View(viewModel);

            // return View(aeronave);
        }

        // POST: Aeronave/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("AeronaveId,TipoAeronave,FechaFabricacion")] AeronaveEditViewModel aeronaveView)
        {
            if (id != aeronaveView.AeronaveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var aeronave = new Aeronave{
                    FechaFabricacion = aeronaveView.FechaFabricacion,
                    TipoAeronave = aeronaveView.TipoAeronave,
                };
                try
                {
                    _context.Update(aeronaveView);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AeronaveExists(aeronaveView.AeronaveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aeronaveView);
        }

        // GET: Aeronave/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Aeronave == null)
            {
                return NotFound();
            }

            var aeronave = await _context.Aeronave
                .FirstOrDefaultAsync(m => m.AeronaveId == id);
            if (aeronave == null)
            {
                return NotFound();
            }
                var viewModel = new AeronaveDeleteViewModel();
                    viewModel.FechaFabricacion = aeronave.FechaFabricacion;
                    viewModel.TipoAeronave = aeronave.TipoAeronave;

            return View(viewModel);
        }


        // POST: Aeronave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Aeronave == null)
            {
                return Problem("Entity set 'AeronaveContext.Aeronave'  is null.");
            }
            var aeronave = await _context.Aeronave.FindAsync(id);
            if (aeronave != null)
            {
                _context.Aeronave.Remove(aeronave);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AeronaveExists(int id)
        {
            return (_context.Aeronave?.Any(e => e.AeronaveId == id)).GetValueOrDefault();
        }
    }
}

Views/Aeronave/Create.cshtml
@model ProyectoPrimerParcial.ViewModels.AeronaveCreateViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Crear Aeronave</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TipoAeronave" class="control-label"></label>
                <input asp-for="TipoAeronave" class="form-control" />
                <span asp-validation-for="TipoAeronave" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <label asp-for="FechaFabricacion" class="control-label"></label>
                <input asp-for="FechaFabricacion" class="form-control" />
                <span asp-validation-for="FechaFabricacion" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Aeronave/Delete.cshtml
@model ProyectoPrimerParcial.ViewModels.AeronaveDeleteViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Aeronave</h1>

<h3>Esta seguro que quiere eliminar esta aeronave?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoAeronave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoAeronave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFabricacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFabricacion)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="AeronaveId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> 
        <br>
        <br>
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Aeronave/Details.cshtml
@using ProyectoPrimerParcial.ViewModels;
@model AeronaveDetailViewModel;

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle de la aeronave</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoAeronave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoAeronave)
        </dd>
            <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFabricacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFabricacion)
        </dd>
    </dl>
    @* <div>
        <ol>
            @foreach (var item in Model.Hangars)
            {
                <li>@item.NombreHangar</li>
            }
        </ol>
    </div>     *@
</div>
@* <div>
    <a asp-action="Edit" asp-route-id="@Model?.AeronaveId" class="btn btn-warning">Editar</a> 
<br> *@
<br>
    <a asp-action="Index">Volver</a>
</div>

Views/Aeronave/Edit.cshtml
@model ProyectoPrimerParcial.ViewModels.AeronaveEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar aeronave</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AeronaveId" />
            <div class="form-group">
                <label asp-for="TipoAeronave" class="control-label"></label>
                <input asp-for="TipoAeronave" class="form-control" />
                <span asp-validation-for="TipoAeronave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFabricacion" class="control-label"></label>
                <input asp-for="FechaFabricacion" class="form-control" />
                <span asp-validation-for="FechaFabricacion" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-success" /> 
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Aeronave/Index.cshtml
@using ProyectoPrimerParcial.ViewModels;
@model AeronaveIndexViewmodels

@{
    ViewData["Title"] = "Index";
}

<h1>Aeronaves</h1>

<p>
    <a asp-action="Create" class="btn btn-success">+ Aeronave</a>
</p>

<div class="row">
    <form method="get" asp-action="Index" asp-controller="Aeronave">
        <div class="col-6 form-group">
            <input class="form-control" asp-for="NameFilter" />
        </div>
        <br>
        <button class="btn btn-info" type="submit">Buscar</button>
    </form>
</div>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipoAeronave)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFabricacion)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.aeronaves) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TipoAeronave)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => item.FechaFabricacion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AeronaveId"class="btn btn-warning">Modificar</a> 
                <a asp-action="Details" asp-route-id="@item.AeronaveId" class="btn btn-primary">Detalle</a> 
                <a asp-action="Delete" asp-route-id="@item.AeronaveId"  class="btn btn-danger" onclick="return confirm('¿Esta seguro que quiere eliminar este instructor?')">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>